### ISSUE TITLE
Media assets from bulk imports with .jpg don't display in the encounterMediaGallery

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#252]
**Expected Behavior**
all supported formats (.png, .jpg, .jpeg) display correctly in the encounter gallery.

**Current Behavior**
`/src/main/webapp/encounters/encounterMediaGallery.jsp`
.jpg that come from a bulk import do not display in the encounter gallery.

_Investigation notes_
`src/main/webapp/import/photos.jsp` is where the bulk import of images happens.

- changing to .jpeg fixes the image.
- .jpgs work in the rest of the platform.
- uploading from a standard import displays correctly. 

**Conclusion**: something with the bulk import processing

**Community Link**
https://community.wildme.org/t/encounter-mediaasset0-column-not-uploading/1238/6

**Comment by NNattoji** [comment]
Tested locally on Flukebook using a whale image from the web. The issue does not happen anymore or appears to have been already fixed or might have happened due to some other reason when it was reported. Images with .jpg extension from bulk import display fine on the media gallery now.

![Parsed_Table](https://github.com/WildMeOrg/Wildbook/assets/20950872/cf89c894-c0a9-48a1-80c8-286303623d4e)

![Import_Completion](https://github.com/WildMeOrg/Wildbook/assets/20950872/818ccf93-c6c7-4ba3-b162-eb112ce89517)

![Image_Gallery](https://github.com/WildMeOrg/Wildbook/assets/20950872/f88883fc-3ce4-4b08-9fe5-315d4997e3d3)

**Comment by TanyaStere42** [comment]
Confirmed on QA to have been resolved at some point previously. Thanks for the double check!
