### ISSUE TITLE
Simplify co-occurrence diagram on individuals.jsp

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#278]
**Desired Behavior**
Make the co-occurrence diagram represent data as-shown in platform rather than attempting predictive calculations.

IMAGE BELOW IS APPROXIMATION. DO NOT DO PIXEL FOR PIXEL REPRESENTATION

![Image](https://github.com/WildMeOrg/Wildbook/assets/62726866/b570f4da-3171-40d3-b7db-5b91011072a0)

_Requirements_
- remove time/space sliders
- visualize the individual and any individuals that share a sighting. represent the shared sighting difference somehow
- be able to filter by sighting

**Current Behavior**
The co-occurrence diagram's attempt to predict co-occurrence based on close time and space relationship is confusing, and most species don't have data to support it. Co-occurrence display should be simplified to only visualize explicit co-occurrence (e.g., individuals with Encounters under the same Occurrence) and remove the time/space sliders.

**Community Link**
https://community.wildme.org/t/co-occurrences-diagram-confusion/435

**Comment by NNattoji** [comment]
The time/space sliders don't show up now, after deleting the corresponding code. 

![Screen Shot 2024-05-03 at 9 28 12 AM](https://github.com/WildMeOrg/Wildbook/assets/20950872/6259de4a-722a-4992-9c00-d76acb0a336a)

Also, the code which updates the spatial/temporal values on the graph has been commented out. The graph now by default shows the count of shared sightings between individuals, instead of spatial/temporal values.

Only those individuals with shared sightings (occurrences) show up on the co-occurrence diagram. I used the below steps to check this:

1. Created individuals 1 and 2 with a shared sighting (occurrence).
2. Created individual 3 with a different sighting (occurrence) 
3. Added the same latitude, longitude and time values for all 3 individuals.

Only individuals 1 and 2 show up on the co-occurrence diagram for the first two individuals, individual 3 does not. 

Looks like the logic to display only those individuals with shared sightings (occurrences) might already have been implemented sometime previously, after this ticket was created. Hence filtering by sighting might not be applicable if only individuals from shared sightings (occurrences) are shown always. But if there is a specific scenario where individuals not having a shared sighting are shown based on spatial/temporal values, I can test it and implement the filters, if the scenario details are provided.

**Comment by NNattoji** [comment]
I tested this before making the code changes. Only those individuals with shared sightings (occurrences) show up on the co-occurrence diagram. I used the below steps to check this:

1. Created individuals 1 and 2 with a shared sighting (occurrence).
2. Created individual 3 with a different sighting (occurrence)
3. Added the same latitude, longitude and time values for all 3 individuals.

Only individuals 1 and 2 show up on the co-occurrence diagram for the first two individuals, individual 3 does not.

Looks like the logic to display only those individuals with shared sightings (occurrences) might already have been implemented sometime previously, after this ticket was created. Hence filtering by sighting might not be applicable if only individuals from shared sightings (occurrences) are shown always. But if there is a specific scenario where individuals not having a shared sighting are shown based on spatial/temporal values, I can test it and implement the filters, if the scenario details are provided.
