### ISSUE TITLE
bulk import page has inconsistent link interactions

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#364]
**Expected Behavior**
Links on the page `/import.jsp?taskId=[guid]` open new tabs to `target=_self`, middle click to `target=_blank`, and right click opens the standard menu

**Current Behavior**

- You can right-click, scroll wheel click, ctrl+click, and cmd+click encounters from a specific bulk import (/import.jsp?taskId=1234) to open them in a new tab.

**Comment by NNattoji** [comment]
Tested this while looking into https://github.com/WildMeOrg/Wildbook/issues/292

This works as expected on my local. The table row 'tr' elements are not clickable here, but the encounters on the first column are anchor 'a' elements with an 'href'. Hence they show the standard link behaviour as expected i.e.

- Click (Left-click) opens with target=_self
- Middle-click and cmd+click opens with target=_blank
- Right-click and ctrl-click opens the menu, with an 'Open link in new tab' option

The inconsistency observed might be due to browser-specific configuration settings on some browsers.

**Comment by TanyaStere42** [comment]
🤔 hmm @goddesswarship can you do some testing on QA and see if you can recreate to pinpoint a specific browser or something causing this?

**Comment by goddesswarship** [comment]
I think this was the one example from the original list that actually was actually working correctly. This was the full list of inconsistent link interactions:

- You **can't** right-click or middle click to open links in a new tab from the bulk import page (`/imports.jsp`) but you **can** Ctrl+click or Cmd+click
- You **can** right-click, middle click, Ctrl+click, and Cmd+click encounters from a specific bulk import (`/import.jsp?taskId=[guid]`) to open them in a new tab.
- When on the match results page (`/iaResults.jsp?taskId=[guid]`), you **can't** right-click, middle click, Ctrl+click, or Cmd+click to view the encounter page of the match candidate in a new tab. It will only open in the same window as the match page.
- From a marked individual page (`/individuals.jsp?id=[guid]`), you **can't** right-click or middle click to open encounter links in a new tab, but you **can** Ctrl+click or Cmd+click.

**Comment by TanyaStere42** [comment]
I'll go ahead and close this then
