### ISSUE TITLE
allow selection of any region on bulk import processing

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#433]
## Feature description and context
BOEM-funded user research indicated this would be one of the greatest usability improvements for the platform. It is common for the first run of a bulk import to be against an existing catalog rather than the broad case of all region data. Allowing user control of what regions are being compared against means that all common processing use cases are supported.

## Feature sign-off requirements
For `import.jsp`
- [ ] dropdown allows for multi-select
- [ ] all regions from `locationID.json` are available in the selector

## Design Reference
![image](https://github.com/WildMeOrg/Wildbook/assets/62726866/a3bffeb9-b4a9-45d1-b9ef-7fb8901cc0e6)

**Comment by TanyaStere42** [comment]
@naknomum QA'd, found to have made the regions box disappear? Need to reopen to address

![image](https://github.com/WildMeOrg/Wildbook/assets/62726866/6d85ca31-357e-4e31-bb0e-148b70de4f9e)

**Comment by naknomum** [comment]
@TanyaStere42 - i see now what the problem is here: i had altered the (already existing) pulldown that was present when the option was **Send to _identification_**.

the above screen grab is the **detection** button, which _never_ had a location pulldown menu. (note: it has "no identification".) do we _want_ locations on this option? it seems to me like not, as location is only used for _identification_ purposes.

from QA, when its the identification one, the menu does seem to appear:
![image](https://github.com/WildMeOrg/Wildbook/assets/901250/d9382a5c-ee9b-47ca-86aa-b336c841ad90)

**Comment by TanyaStere42** [comment]
Great, awesome, @goddesswarship has confirmed that's how this works now. I was remembering a legacy workflow :sob: This is done!
