### ISSUE TITLE
pom standardization

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#839]
## Feature description and context
As we're upgrade our VMs and production servers, we're running into inconsistencies between `pom.xml` files. We need to do a full verification across production instances and push to `main` the finalized version of `pom.xml`

## Feature sign-off requirements
- test the new maven plugin version. at time of writing:
```
diff --git a/pom.xml b/pom.xml
index 40a76ed7f..86bafb37b 100644
--- a/pom.xml
+++ b/pom.xml
@@ -676,7 +676,7 @@
       </plugin>
       <plugin>
         <artifactId>maven-war-plugin</artifactId>
-        <version>2.2</version>
+        <version>3.3.2</version>
```
- seals has more of a diff -- which includes some json/jackson stuff which i also recall was weirdly inconsistent between vm/dockers, related to opensearch indexing

**Comment by naknomum** [comment]
NOTE: this should be the _only_ change to the pom for this ticket.  in particular, there were these 2 dependencies which _seemed_ to be needed in our production environment, but turned out to be (we think!) tied to erroneously using OpenSearch `latest` docker image. instead we should stay using a fixed (2.15.0 at this time) OpenSearch docker image.

```
    <dependency>
      <groupId>org.glassfish</groupId>
      <artifactId>javax.json</artifactId>
      <version>1.1.4</version>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.9.1</version>
    </dependency>
```
